export { default as crearComida } from './crearComida'
export { default as obtenerUnaComida } from './obtenerUnaComida'
export { default as obtenerComidasRestaurante } from './obtenerComidasRestaurante'
export { default as obtenerComidasValoradasPorComensal } from './obtenerComidasValoradasPorComensal'
export { default as obtenerTodasLasComidas } from './obtenerTodasLasComidas'
export { default as editarComida } from './editarComida'
export { default as borrarComida } from './borrarComida'