export { default as crearComida } from './crearComida'
export { default as obtenerUnaComida } from './obtenerUnaComida'
export { default as obtenerComidas } from './obtenerComidas'
export { default as editarComida } from './editarComida'
export { default as borrarComida } from './borrarComida'