export { default as InfoDeLaPagina } from './InfoDeLaPagina'
export { default as IniciarSesion } from './IniciarSesion'
export { default as Inicio } from './Inicio'
export { default as RecuperarPassword } from './RecuperarPassword'
export { default as Registro } from './Registro'
export { default as RegistroComensal } from './RegistroComensal'
export { default as RegistroRestaurante } from './RegistroRestaurante'