export { default as CarouselInicio } from './CarouselInicio'
export { default as FoodCard } from './FoodCard'
export { default as InformacionRestaurante } from './InformacionRestaurante'
export { default as StarRating } from './StarRating'
export { default as DragDropImageUploader } from './DragDropImageUploader'
export { default as BorrarValoracion } from './BorrarValoracion'
export { default as EditarUnaComida } from './EditarUnaComida'
export { default as BorrarComida } from './BorrarComida'